package entidades;
// Generated 22/10/2020 03:51:54 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Exame generated by hbm2java
 */
public class Exame  implements java.io.Serializable {


     private int idExame;
     private Pessoa pessoa;
     private TipoExame tipoExame;
     private Date dataPostagem;
     private Date dataValidade;
     private String arquivo;
    
    public Exame() {
    }

	
    public Exame(int idExame) {
        this.idExame = idExame;
    }
    public Exame(int idExame, Pessoa pessoa, TipoExame tipoExame, Date dataPostagem, Date dataValidade, String arquivo) {
       this.idExame = idExame;
       this.pessoa = pessoa;
       this.tipoExame = tipoExame;
       this.dataPostagem = dataPostagem;
       this.dataValidade = dataValidade;
       this.arquivo = arquivo;
    }
   
    public int getIdExame() {
        return this.idExame;
    }
    
    public void setIdExame(int idExame) {
        this.idExame = idExame;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public TipoExame getTipoExame() {
        return this.tipoExame;
    }
    
    public void setTipoExame(TipoExame tipoExame) {
        this.tipoExame = tipoExame;
    }
    public Date getDataPostagem() {
        return this.dataPostagem;
    }
    
    public void setDataPostagem(Date dataPostagem) {
        this.dataPostagem = dataPostagem;
    }
    public Date getDataValidade() {
        return this.dataValidade;
    }
    
    public void setDataValidade(Date dataValidade) {
        this.dataValidade = dataValidade;
    }
    public String getArquivo() {
        return this.arquivo;
    }
    
    public void setArquivo(String arquivo) {
        this.arquivo = arquivo;
    }




}


