package entidades;
// Generated 22/10/2020 03:51:54 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pessoa generated by hbm2java
 */
public class Pessoa  implements java.io.Serializable {


     private int idPessoa;
     private Cidade cidade;
     private String nomePessoa;
     private String cpf;
     private String rg;
     private Date dataNasc;
     private String email;
     private Boolean adm;
     private String rua;
     private String bairro;
     private String numero;
     private String complemento;
     private Set exames = new HashSet(0);
     private Set telefones = new HashSet(0);

    public Pessoa() {
    }

	
    public Pessoa(int idPessoa) {
        this.idPessoa = idPessoa;
    }
    public Pessoa(int idPessoa, Cidade cidade, Telefone telefone, String nomePessoa, String cpf, String rg, Date dataNasc, String email, Boolean adm, String rua, String bairro, String numero, String complemento, Set exames) {
       this.idPessoa = idPessoa;
       this.cidade = cidade;
       this.nomePessoa = nomePessoa;
       this.cpf = cpf;
       this.rg = rg;
       this.dataNasc = dataNasc;
       this.email = email;
       this.adm = adm;
       this.rua = rua;
       this.bairro = bairro;
       this.numero = numero;
       this.complemento = complemento;
       this.exames = exames;
    }
   
    public int getIdPessoa() {
        return this.idPessoa;
    }
    
    public void setIdPessoa(int idPessoa) {
        this.idPessoa = idPessoa;
    }
    public Cidade getCidade() {
        return this.cidade;
    }
    
    public void setCidade(Cidade cidade) {
        this.cidade = cidade;
    }

    public Set getTelefones() {
        return telefones;
    }

    public void setTelefones(Set telefones) {
        this.telefones = telefones;
    }
    
    public String getNomePessoa() {
        return this.nomePessoa;
    }
    
    public void setNomePessoa(String nomePessoa) {
        this.nomePessoa = nomePessoa;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public String getRg() {
        return this.rg;
    }
    
    public void setRg(String rg) {
        this.rg = rg;
    }
    public Date getDataNasc() {
        return this.dataNasc;
    }
    
    public void setDataNasc(Date dataNasc) {
        this.dataNasc = dataNasc;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Boolean getAdm() {
        return this.adm;
    }
    
    public void setAdm(Boolean adm) {
        this.adm = adm;
    }
    public String getRua() {
        return this.rua;
    }
    
    public void setRua(String rua) {
        this.rua = rua;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public String getComplemento() {
        return this.complemento;
    }
    
    public void setComplemento(String complemento) {
        this.complemento = complemento;
    }
    public Set getExames() {
        return this.exames;
    }
    
    public void setExames(Set exames) {
        this.exames = exames;
    }
    
    public Exame getExame(int id) {
        for(Exame exame:(Set<Exame>)exames){
            if(exame.getIdExame()==id){
                return exame;
            }
        }
        return null;
    }




}


