package entidades;
// Generated 22/10/2020 03:51:54 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoExame generated by hbm2java
 */
public class TipoExame  implements java.io.Serializable {


     private int idTipoExame;
     private String nomeTipo;
     private Integer tempoValidade;
     private Set exames = new HashSet(0);

     @Override
    public String toString(){
        return nomeTipo;
    }
    
    public TipoExame() {
    }

	
    public TipoExame(int idTipoExame) {
        this.idTipoExame = idTipoExame;
    }
    public TipoExame(int idTipoExame, String nomeTipo, Integer tempoValidade, Set exames) {
       this.idTipoExame = idTipoExame;
       this.nomeTipo = nomeTipo;
       this.tempoValidade = tempoValidade;
       this.exames = exames;
    }
   
    public int getIdTipoExame() {
        return this.idTipoExame;
    }
    
    public void setIdTipoExame(int idTipoExame) {
        this.idTipoExame = idTipoExame;
    }
    public String getNomeTipo() {
        return this.nomeTipo;
    }
    
    public void setNomeTipo(String nomeTipo) {
        this.nomeTipo = nomeTipo;
    }
    public Integer getTempoValidade() {
        return this.tempoValidade;
    }
    
    public void setTempoValidade(Integer tempoValidade) {
        this.tempoValidade = tempoValidade;
    }
    public Set getExames() {
        return this.exames;
    }
    
    public void setExames(Set exames) {
        this.exames = exames;
    }




}


